# Site settings
title: Babel
tagline: The compiler for writing next generation JavaScript
description: The compiler for writing next generation JavaScript
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://babeljs.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: babel
exclude: ["node_modules"]

# Build settings
markdown: redcarpet
# markdown: kramdown
highlighter: pygments

redcarpet:
  extensions: ['tables', 'no_intra_emphasis', 'autolink', 'with_toc_data']

# kramdown:
#   input: GFM
#   hard_wrap: false

# Blog Settings
permalink: /blog/:year/:month/:day/:title
paginate: 1

gems:
  - jekyll-redirect-from
